# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: github-action-matrix-outputs-write
  description: Workaround implementation - Write matrix jobs outputs
  homepage: https://github.com/community/community/discussions/17245#discussioncomment-3814009
  topics: ""

